name: finish_up_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.10
  go_router: ^10.1.2
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  freezed: ^2.4.2
  freezed_annotation: ^2.4.1
  firebase_core: ^2.15.1
  sqflite: ^2.3.0
  cloud_firestore: ^4.9.1
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_native_splash: ^2.3.2

flutter:
  uses-material-design: true
  fonts:
    - family: Kumbh
      fonts:
        - asset: assets/fonts/kumbh_sans/KumbhSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/kumbh_sans/KumbhSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/kumbh_sans/KumbhSans-Light.ttf
          weight: 300
        - asset: assets/fonts/kumbh_sans/KumbhSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/kumbh_sans/KumbhSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/kumbh_sans/KumbhSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/kumbh_sans/KumbhSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/kumbh_sans/KumbhSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/kumbh_sans/KumbhSans-Black.ttf
          weight: 900

flutter_native_splash:
  image: assets/images/logo.png
  color: "#fdfdfd"
  android_12:
    image: assets/images/splash_logo.png
    color: "#fdfdfd"
    image_dark: assets/images/splash_logo_dark.png
    color_dark: "#020202"
    #branding: assets/images/logo.png
  #fullscreen: true
